### ISSUE TITLE
enforcing jira id in git-conventional-commits.yaml 

### ISSUE THREAD

**Issue by timurcatakli** [Blazity/next-enterprise#141]
Hi there, first of all this is an amazing repo. thanks a lot. Quick question: How can I enforce below in my commits:

```
issueRegexPattern: "[A-Z][A-Z0-9]+-[0-9]+"
issueUrl: https://WORKSPACE.atlassian.net/browse/%issue%
```
uncommenting them did not help...
Thank you,

**Comment by bmstefanski** [comment]
Hello, thanks! I the following regex pattern doesn't work for you, please create an issue here https://github.com/qoomon/git-conventional-commits
