### ISSUE TITLE
Tooltip/Radix-UI - Fetch Primitive error

### ISSUE THREAD

**Issue by cassa36** [Blazity/next-enterprise#143]
I am trying to implement the ToolTip component that comes with Next-Enterprise. I added the explainer and the children - but when I to my browser it is having trouble pulling Primitive from /nextjs-enterprise-boilerplate/node_modules/@radix-ui/react-popper/dist/index.mjs (7)

import pkg from '@radix-ui/react-primitive';
const {Primitive: $kY93V$Primitive} = pkg;

SyntaxError: Named export 'Primitive' not found. The requested module '@radix-ui/react-primitive' is a CommonJS module, which may not support all module.exports as named exports.

**Comment by bmstefanski** [comment]
Hey, I will take a look at it soon

**Comment by bmstefanski** [comment]
✅
