### ISSUE TITLE
The theme you showcased on next.js website is not same as what I see in your template

### ISSUE THREAD

**Issue by Aravin** [Blazity/next-enterprise#267]
Hi Team,

I have deployed your project into Vercel & I could see only 

your demo: https://blazity.com/open-source/nextjs-enterprise-boilerplate
but actual template: https://nextjs-enterprise-boilerplate-mu-three.vercel.app/ 

Please let me know if am missing something

**Comment by bmstefanski** [comment]
Hi! 

We do redirect the deployed version to our company's domain, but it shouldn't affect the way it displays on your deployed instance. 

The template in demo uses our private design system for consistent branding, but it's still the same template, just different colors and container :)

**Comment by Aravin** [comment]
Thanks for closing the bug :)
