### ISSUE TITLE
How to add new page from boilerplate like i can do it with NextJs starter?

### ISSUE THREAD

**Issue by akhilchhetri** [Blazity/next-enterprise#297]
- I want to add more pages from the boilerplate, I can see app/page.tsx for index, Do i need to create own routes to handle routing or NextJS pattern should work? 
- I created pages directory in root dir and added few pages, it works but styles are not loaded from the components imported.

**Comment by bmstefanski** [comment]
Hi,

This project fully supports app directory and pages directory. Use whatever suits your needs best.

I recommend this doc to learn more about routing in Next.js https://nextjs.org/learn/dashboard-app/creating-layouts-and-pages

Thanks!
