### ISSUE TITLE
Issue with icons on MacOS and iOS safari

### ISSUE THREAD

**Issue by szymon-wiatr** [Blazity/next-enterprise#80]
Hi,
This project is awesome! 
Good job guys.

I am facing issue with the icons. It happens only on safari (desktop + mobile)

It is fine on desktop chrome & firefox.

<img width="878" alt="safari-desktop-icons" src="https://github.com/Blazity/next-enterprise/assets/1669730/c06a3c31-0cb5-47fb-855a-5562f8bdf407">

![IMG_5249](https://github.com/Blazity/next-enterprise/assets/1669730/ce9423fe-b0e2-417f-9b8e-f83480714891)

**Comment by bmstefanski** [comment]
Thanks for reporting, safari is struggiling (as always) to get the width and height of the icons from the container, will fix it soon
